model:
  base_learning_rate: 4.5e-6
  target: sgm.models.autoencoder.AutoencoderKL
  params:
    input_key: jpg
    monitor: "val/loss/rec"
    disc_start_iter: 50001
    embed_dim: 16
    ckpt_path: files/vae.safetensors
    scaling_factor: 1.5305
    shift_factor: 0
    trainable_ae_params: null
    use_fp16: false

    ddconfig:
      attn_type: vanilla-sdp
      double_z: false
      z_channels: 16
      resolution: 1024
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [1, 2, 4, 4]
      num_res_blocks: 2
      attn_resolutions: []
      dropout: 0.0
      act_fn: silu
      use_post_quant_conv: false
      use_quant_conv: false
      mid_block_add_attention: true
      force_upcast: true
      norm_num_groups: 32

    lossconfig:
      target: sgm.modules.autoencoding.losses.GeneralLPIPSWithDiscriminator
      params:
        perceptual_weight: 0.1
        disc_start: 50001
        disc_weight: 0.0
        learn_logvar: false
        pixel_loss: "l2"
        regularization_weights:
          kl_loss: 1.0e-6

data:
  target: sgm.data.imagenet.ImageNetLoader
  params:
    batch_size: 24
    num_workers: 4
    prefetch_factor: 2
    shuffle: true

    train:
      root_dir: /path/to/ImageNet
      size: 1024
      transform: true
    validation:
      root_dir: /path/to/ImageNet
      size: 1024
      transform: true

lightning:
  strategy:
    target: pytorch_lightning.strategies.DDPStrategy
    params:
      find_unused_parameters: False
      static_graph: True
      gradient_as_bucket_view: True

  modelcheckpoint:
    params:
      every_n_epochs: 1

  callbacks:
    metrics_over_trainsteps_checkpoint:
      params:
        every_n_train_steps: 50000

    image_logger:
      target: main.ImageLogger
      params:
        enable_autocast: False
        batch_frequency: 1000
        max_images: 8
        increase_log_steps: True

  trainer:
    precision: 32
    devices: 0,1,2,3,4,5,6,7
    limit_val_batches: 50
    benchmark: True
    accumulate_grad_batches: 1
    check_val_every_n_epoch: 1
